[package]
name = "bitwarden"
version = "0.3.1"
authors = ["Bitwarden Inc"]
license-file = "LICENSE"
repository = "https://github.com/bitwarden/sdk"
homepage = "https://bitwarden.com"
description = """
Bitwarden Secrets Manager SDK
"""
keywords = ["bitwarden", "secrets-manager"]
edition = "2021"
rust-version = "1.57"

[features]
default = ["secrets"]

secrets = []                    # Secrets manager API
internal = []                   # Internal testing methods
mobile = ["uniffi", "internal"] # Mobile-specific features

[dependencies]
base64 = ">=0.21.2, <0.22"
lazy_static = ">=1.4.0, <2.0"
reqwest = { version = ">=0.11, <0.12", features = ["json"] }
serde = { version = ">=1.0, <2.0", features = ["derive"] }
serde_json = ">=1.0.96, <2.0"
serde_qs = ">=0.12.0, <0.13"
serde_repr = ">=0.1.12, <0.2"
schemars = { version = ">=0.8, <0.9", features = ["uuid1", "chrono"] }
log = ">=0.4.18, <0.5"
assert_matches = ">=1.5.0, <2.0"
thiserror = ">=1.0.40, <2.0"
aes = ">=0.8.2, <0.9"
cbc = { version = ">=0.1.2, <0.2", features = ["alloc"] }
hkdf = ">=0.12.3, <0.13"
hmac = ">=0.12.1, <0.13"
rsa = ">=0.9.2, <0.10"
sha1 = ">=0.10.5, <0.11"
sha2 = ">=0.10.6, <0.11"
pbkdf2 = { version = ">=0.12.1, <0.13", default-features = false }
argon2 = { version = ">=0.5.0, <0.6", features = [
    "alloc",
], default-features = false }
rand = ">=0.8.5, <0.9"
num-bigint = ">=0.4, <0.5"
num-traits = ">=0.2.15, <0.3"
uuid = { version = ">=1.3.3, <2.0", features = ["serde"] }
chrono = { version = ">=0.4.26, <0.5", features = [
    "serde",
    "std",
], default-features = false }
uniffi = { version = "=0.24.1", optional = true }

# We don't use this directly (it's used by rand), but we need it here to enable WASM support
getrandom = { version = ">=0.2.9", features = ["js"] }

bitwarden-api-identity = { path = "../bitwarden-api-identity", version = "=0.2.2" }
bitwarden-api-api = { path = "../bitwarden-api-api", version = "=0.2.2" }

[dev-dependencies]
tokio = { version = "1.28.2", features = ["rt", "macros"] }
wiremock = "0.5.18"
