name: Generate schemas

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  schemas:
    name: Generate schemas
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Install rust
        uses: dtolnay/rust-toolchain@439cf607258077187679211f12aa6f19af4a0af7 # stable
        with:
          toolchain: stable

      - name: Set up Node
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          cache: "npm"
          cache-dependency-path: "package-lock.json"
          node-version: "16"

      - name: NPM setup
        run: npm ci

      - name: Cache cargo registry
        uses: Swatinem/rust-cache@a95ba195448af2da9b00fb742d14ffaaf3c21f43 # v2.7.0

      - name: NPM Schemas
        run: npm run schemas

      - name: Upload ts schemas artifact
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: schemas.ts
          path: ${{ github.workspace }}/languages/js_webassembly/bitwarden_client/schemas.ts
          if-no-files-found: error

      - name: Upload c# schemas artifact
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: schemas.cs
          path: ${{ github.workspace }}/languages/csharp/Bitwarden.Sdk/schemas.cs
          if-no-files-found: error

      - name: Upload python schemas artifact
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: schemas.py
          path: ${{ github.workspace }}/languages/python/BitwardenClient/schemas.py
          if-no-files-found: error

      - name: Upload json schemas artifact
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: sdk-schemas-json
          path: ${{ github.workspace }}/support/schemas/*
          if-no-files-found: error

      - name: Upload cpp schemas artifact
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: schemas.cpp
          path: ${{ github.workspace }}/languages/cpp/schemas.cpp
          if-no-files-found: error
