name: test

on:
  # pull_request:
  #   branches:
  #     - master
  workflow_dispatch:

env:
  LIBS_PATH: ${{ github.workspace }}/libs

jobs:
  build_cpp:
    name: Build C++
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          # - windows-2022
          - ubuntu-22.04
          - macos-12
        compiler:
          - llvm
        prefix:
          - lib
        include:
          # - os: windows-2022
          #   architecture: x86_64
          #   compiler: msvc
          #   extension: dll
          #   target: x86_64-pc-windows-msvc
          #   prefix: ""
          - os: ubuntu-22.04
            architecture: x86_64
            extension: so
            target: x86_64-linux-gnu
          - os: macos-12
            architecture: x86_64
            extension: dylib
            target: x86_64-apple-macos12
          - os: macos-12
            architecture: arm64
            extension: dylib
            target: arm64-apple-macos12
    steps:
      - name: Setup C++
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows') }}
          cmake: true
          ninja: true
          vcpkg: true
          cppcheck: true
          clangtidy: true
